version: '3.8'
 
services:
    web:
        build: .
        container_name: cv
        restart: always
        networks:
            - nginproxymanager_default 

networks:
    nginproxymanager_default:
        external: true
volumes: